on: [push, pull_request]

name: Project Quality Check

jobs:
  fmt:
    name: Run `cargo fmt --all -- --check`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install `rust` toolchain
        run: |
          ## Install `rust` toolchain
          rustup toolchain install stable --no-self-update -c rustfmt --profile minimal
          rustup default stable
      - name: Setup `rustfmt`
        run: rustup component add rustfmt
      - name: cargo fmt
        run: |
          cargo fmt --all -- --check

  clippy:
    name: Run `cargo clippy -- -D warnings`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install `rust` toolchain
        run: |
          ## Install `rust` toolchain
          rustup toolchain install stable --no-self-update -c rustfmt --profile minimal
          rustup default stable
      - name: Setup `clippy`
        run: rustup component add clippy
      - name: Run `cargo clippy`
        run: |
          cargo clippy --all-targets -- -D warnings

  compose:
    name: Run `docker compose build`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build docker compose
        run: docker compose build
